// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const checkExists = `-- name: CheckExists :one
SELECT id FROM vouchers 
WHERE flight_number = ?1 AND flight_date = ?2 LIMIT 1
`

type CheckExistsParams struct {
	FlightNumber string `json:"flight_number"`
	FlightDate   string `json:"flight_date"`
}

func (q *Queries) CheckExists(ctx context.Context, arg CheckExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkExists, arg.FlightNumber, arg.FlightDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertVoucher = `-- name: InsertVoucher :exec
INSERT INTO vouchers (
    crew_name, crew_id, flight_number, flight_date, aircraft_type, seat1, seat2, seat3, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertVoucherParams struct {
	CrewName     string `json:"crew_name"`
	CrewID       string `json:"crew_id"`
	FlightNumber string `json:"flight_number"`
	FlightDate   string `json:"flight_date"`
	AircraftType string `json:"aircraft_type"`
	Seat1        string `json:"seat1"`
	Seat2        string `json:"seat2"`
	Seat3        string `json:"seat3"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) InsertVoucher(ctx context.Context, arg InsertVoucherParams) error {
	_, err := q.db.ExecContext(ctx, insertVoucher,
		arg.CrewName,
		arg.CrewID,
		arg.FlightNumber,
		arg.FlightDate,
		arg.AircraftType,
		arg.Seat1,
		arg.Seat2,
		arg.Seat3,
		arg.CreatedAt,
	)
	return err
}
