// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"airline-voucher/backend/handler"
	"airline-voucher/backend/repository"
	"airline-voucher/backend/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializeHandler(db *sql.DB) (*handler.VoucherHandler, error) {
	voucherRepository := repository.NewVoucherRepository(db)
	voucherService := usecase.NewVoucherService(voucherRepository)
	voucherHandler := handler.NewVoucherHandler(voucherService)
	return voucherHandler, nil
}
